#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgit2
Version  : 1.6.1
Release  : 41
URL      : https://github.com/libgit2/libgit2/archive/v1.6.1/libgit2-1.6.1.tar.gz
Source0  : https://github.com/libgit2/libgit2/archive/v1.6.1/libgit2-1.6.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 LGPL-2.1 MIT Zlib
Requires: libgit2-bin = %{version}-%{release}
Requires: libgit2-lib = %{version}-%{release}
Requires: libgit2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : libssh2-dev
BuildRequires : openssl-dev
BuildRequires : pcre2-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libcurl)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libgit2 - the Git linkable library
==================================
| Build Status | |
| ------------ | - |
| **main** branch CI builds | [![CI Build](https://github.com/libgit2/libgit2/workflows/CI%20Build/badge.svg?event=push)](https://github.com/libgit2/libgit2/actions?query=workflow%3A%22CI+Build%22+event%3Apush) |
| **v1.6 branch** CI builds | [![CI Build](https://github.com/libgit2/libgit2/workflows/CI%20Build/badge.svg?branch=maint%2Fv1.6&event=push)](https://github.com/libgit2/libgit2/actions?query=workflow%3A%22CI+Build%22+event%3Apush+branch%3Amaint%2Fv1.6) |
| **v1.5 branch** CI builds | [![CI Build](https://github.com/libgit2/libgit2/workflows/CI%20Build/badge.svg?branch=maint%2Fv1.5&event=push)](https://github.com/libgit2/libgit2/actions?query=workflow%3A%22CI+Build%22+event%3Apush+branch%3Amaint%2Fv1.5) |
| **Nightly** builds | [![Nightly Build](https://github.com/libgit2/libgit2/workflows/Nightly%20Build/badge.svg)](https://github.com/libgit2/libgit2/actions?query=workflow%3A%22Nightly+Build%22) [![Coverity Scan Status](https://scan.coverity.com/projects/639/badge.svg)](https://scan.coverity.com/projects/639) |

%package bin
Summary: bin components for the libgit2 package.
Group: Binaries
Requires: libgit2-license = %{version}-%{release}

%description bin
bin components for the libgit2 package.


%package dev
Summary: dev components for the libgit2 package.
Group: Development
Requires: libgit2-lib = %{version}-%{release}
Requires: libgit2-bin = %{version}-%{release}
Provides: libgit2-devel = %{version}-%{release}
Requires: libgit2 = %{version}-%{release}

%description dev
dev components for the libgit2 package.


%package lib
Summary: lib components for the libgit2 package.
Group: Libraries
Requires: libgit2-license = %{version}-%{release}

%description lib
lib components for the libgit2 package.


%package license
Summary: license components for the libgit2 package.
Group: Default

%description license
license components for the libgit2 package.


%prep
%setup -q -n libgit2-1.6.1
cd %{_builddir}/libgit2-1.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1677518633
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake .. -DREGEX_BACKEND=pcre2 \
-DUSE_SSH=ON
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1677518633
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libgit2
cp %{_builddir}/libgit2-%{version}/deps/http-parser/COPYING %{buildroot}/usr/share/package-licenses/libgit2/1a00a507fb89bb0018c092d6835077d541e76dc2 || :
cp %{_builddir}/libgit2-%{version}/deps/pcre/LICENCE %{buildroot}/usr/share/package-licenses/libgit2/11ff082389982b8168263850db69199065f2028d || :
cp %{_builddir}/libgit2-%{version}/deps/pcre/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/libgit2/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
cp %{_builddir}/libgit2-%{version}/deps/winhttp/COPYING.GPL %{buildroot}/usr/share/package-licenses/libgit2/302250717721b22e804054f10e5a8d9c6e7328c4 || :
cp %{_builddir}/libgit2-%{version}/deps/winhttp/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libgit2/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/libgit2-%{version}/deps/zlib/COPYING %{buildroot}/usr/share/package-licenses/libgit2/07821586dcc816d67ff045b9708fe8291fd67e62 || :
cp %{_builddir}/libgit2-%{version}/examples/COPYING %{buildroot}/usr/share/package-licenses/libgit2/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/git2

%files dev
%defattr(-,root,root,-)
/usr/include/git2.h
/usr/include/git2/annotated_commit.h
/usr/include/git2/apply.h
/usr/include/git2/attr.h
/usr/include/git2/blame.h
/usr/include/git2/blob.h
/usr/include/git2/branch.h
/usr/include/git2/buffer.h
/usr/include/git2/cert.h
/usr/include/git2/checkout.h
/usr/include/git2/cherrypick.h
/usr/include/git2/clone.h
/usr/include/git2/commit.h
/usr/include/git2/common.h
/usr/include/git2/config.h
/usr/include/git2/cred_helpers.h
/usr/include/git2/credential.h
/usr/include/git2/credential_helpers.h
/usr/include/git2/deprecated.h
/usr/include/git2/describe.h
/usr/include/git2/diff.h
/usr/include/git2/email.h
/usr/include/git2/errors.h
/usr/include/git2/experimental.h
/usr/include/git2/filter.h
/usr/include/git2/global.h
/usr/include/git2/graph.h
/usr/include/git2/ignore.h
/usr/include/git2/index.h
/usr/include/git2/indexer.h
/usr/include/git2/mailmap.h
/usr/include/git2/merge.h
/usr/include/git2/message.h
/usr/include/git2/net.h
/usr/include/git2/notes.h
/usr/include/git2/object.h
/usr/include/git2/odb.h
/usr/include/git2/odb_backend.h
/usr/include/git2/oid.h
/usr/include/git2/oidarray.h
/usr/include/git2/pack.h
/usr/include/git2/patch.h
/usr/include/git2/pathspec.h
/usr/include/git2/proxy.h
/usr/include/git2/rebase.h
/usr/include/git2/refdb.h
/usr/include/git2/reflog.h
/usr/include/git2/refs.h
/usr/include/git2/refspec.h
/usr/include/git2/remote.h
/usr/include/git2/repository.h
/usr/include/git2/reset.h
/usr/include/git2/revert.h
/usr/include/git2/revparse.h
/usr/include/git2/revwalk.h
/usr/include/git2/signature.h
/usr/include/git2/stash.h
/usr/include/git2/status.h
/usr/include/git2/stdint.h
/usr/include/git2/strarray.h
/usr/include/git2/submodule.h
/usr/include/git2/sys/alloc.h
/usr/include/git2/sys/commit.h
/usr/include/git2/sys/commit_graph.h
/usr/include/git2/sys/config.h
/usr/include/git2/sys/cred.h
/usr/include/git2/sys/credential.h
/usr/include/git2/sys/diff.h
/usr/include/git2/sys/email.h
/usr/include/git2/sys/filter.h
/usr/include/git2/sys/hashsig.h
/usr/include/git2/sys/index.h
/usr/include/git2/sys/mempack.h
/usr/include/git2/sys/merge.h
/usr/include/git2/sys/midx.h
/usr/include/git2/sys/odb_backend.h
/usr/include/git2/sys/openssl.h
/usr/include/git2/sys/path.h
/usr/include/git2/sys/refdb_backend.h
/usr/include/git2/sys/reflog.h
/usr/include/git2/sys/refs.h
/usr/include/git2/sys/remote.h
/usr/include/git2/sys/repository.h
/usr/include/git2/sys/stream.h
/usr/include/git2/sys/transport.h
/usr/include/git2/tag.h
/usr/include/git2/trace.h
/usr/include/git2/transaction.h
/usr/include/git2/transport.h
/usr/include/git2/tree.h
/usr/include/git2/types.h
/usr/include/git2/version.h
/usr/include/git2/worktree.h
/usr/lib64/libgit2.so
/usr/lib64/pkgconfig/git2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgit2.so.1.6
/usr/lib64/libgit2.so.1.6.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgit2/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libgit2/07821586dcc816d67ff045b9708fe8291fd67e62
/usr/share/package-licenses/libgit2/11ff082389982b8168263850db69199065f2028d
/usr/share/package-licenses/libgit2/1a00a507fb89bb0018c092d6835077d541e76dc2
/usr/share/package-licenses/libgit2/302250717721b22e804054f10e5a8d9c6e7328c4
/usr/share/package-licenses/libgit2/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/libgit2/ff3ed70db4739b3c6747c7f624fe2bad70802987
